### ISSUE TITLE
wma, wav, bmp attachment extensions are converted to "X-MS-WMA", "X-WAV", "X-MS-BMP"

### ISSUE THREAD

**Issue by BorisWiggers** [attdevsupport/att-sdk-android#77]
Steps:
1) Create a new MMS message
2) Attach a wma, wav, bmp file (i.e. bananas.wma or bananas.wav, test.bmp)
3) Send msg
4) Receive, open message.
5) Try to open the attachment

Result:
1) Attachment has been converted from a wma, wav, bmp to "X-MS-WMA","X-WAV","X-MS-BMP" extensions.
2) Get an error when trying to open the attachment; see screen shot below.

Expected:
1) Use to be able to properly send, receive and open wma, wav bananas, or test.bmp example files.

Notes:
1) amr and mp3 sound files don't seem to be getting converted with another extension.
2) mp4 movie files are also not being converted.

![screenshot_2014-04-10-13-13-46](https://cloud.githubusercontent.com/assets/5348486/2672973/60a0d0b8-c0ed-11e3-968f-a959c4959244.png)

**Comment by tarasklimenko** [comment]
Only Speex file type supported.
